server:
  port: 0
  
spring:
  application:
    name: twitter-clone-follow-service
  datasource:
    url: jdbc:mysql://mysql:3307/twitter_clone
    username: root
    password: root
  jpa:

    hibernate:
      ddl-auto: update
      

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true