server:
  port: 8081

spring:
  application:
    name: twitter-clone-auth-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/twitter_clone
    username: root
    password: root
  jpa:

    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true