version: "3.8"

services:
  discovery-server:
    image: eureka-server
    build: ./discovery-server
    ports:
      - "8761:8761"

  config-server:
    image: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  api-gateway:
    image: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server

  auth-service:
    image: auth-service
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - config-server

  user-service:
    image: user-service
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - config-server

  tweet-service:
    image: tweet-service
    build: ./tweet-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
      - config-server

  follow-service:
    image: follow-service
    build: ./follow-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
      - config-server

  notification-service:
    image: notification-service
    build: ./notification-service
    ports:
      - "8085:8085"
    depends_on:
      - discovery-server
      - config-server

  timeline-service:
    image: timeline-service
    build: ./timeline-service
    ports:
      - "8086:8086"
    depends_on:
      - discovery-server
      - config-server

  like/retweet-service:
    image: like/retweet-service
    build: ./like/retweet-service
    ports:
      - "8087:8087"
    depends_on:
      - discovery-server
      - config-server
