services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter_clone
    ports:
      - "3307:3306"
    networks:
      - twitter-clone-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    image: eureka-server
    container_name: discovery-server
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    ports:
      - "8762:8762" # Cambia 8761 por 8762
    networks:
      - twitter-clone-network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - twitter-clone-network
    restart: always

  auth-service:
    image: auth-service
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - twitter-clone-network
    restart: always

  user-service:
    image: user-service
    container_name: user-service
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - twitter-clone-network
    restart: always

  tweet-service:
    image: tweet-service
    container_name: tweet-service
    build:
      context: .
      dockerfile: tweet-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - twitter-clone-network
    restart: always

  follow-service:
    image: follow-service
    container_name: follow-service
    build:
      context: .
      dockerfile: follow-service/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - twitter-clone-network
    restart: always

networks:
  twitter-clone-network:
    driver: bridge
