services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitter_clone
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - twitter-clone-network

  discovery-server:
    image: eureka-server
    build: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - twitter-clone-network

  api-gateway:
    image: api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    networks:
      - twitter-clone-network

  auth-service:
    image: auth-service
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
    networks:
      - twitter-clone-network

  user-service:
    image: user-service
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
    networks:
      - twitter-clone-network

  tweet-service:
    image: tweet-service
    build: ./tweet-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
    networks:
      - twitter-clone-network

  #follow-service:
  #  image: follow-service
  #  build: ./follow-service
  #  ports:
  #    - "8084:8084"
  #  depends_on:
  #    - discovery-server
  #  networks:
  #    - twitter-clone-network



networks:
  twitter-clone-network:
    driver: bridge
