server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/users/**
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: tweet-service
          uri: http://tweet-service:8083
          predicates:
            - Path=/tweets/**
        - id: follow-service
          uri: http://follow-service:8084
          predicates:
            - Path=/follows/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
