server:
  port: 8082

spring:
  application:
    name: twitter-clone-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/twitter_clone
    username: root
    password: root
  jpa:

    hibernate:
      ddl-auto: update
      

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true